In [105]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

df = pd.read_excel('https://www.eia.gov/electricity/data/state/annual_generation_state.xls')
df.columns = ["Year","State", "Type of Producer", "Energy Source", "Total Energy Generated(MWh)"]
df = df[df["Type of Producer"].str.contains("Total Electric Power Industry")]
df = df[df["Energy Source"].str.contains("Total|Hydroelectric Conventional|Wind|Solar Thermal and Photovoltaic")]
years = [2011,2012,2013,2014,2015,2016,2017,2018]
df = df[df["Year"].isin(years)]
df_total_energy_generated = df[df["Energy Source"].str.contains("Total")]
df_rewable_energy_generated = df[df["Energy Source"].str.contains("Hydroelectric Conventional|Wind|Solar Thermal and Photovoltaic|Pumped Storage")]
df_new = df_rewable_energy_generated.groupby(['Year','State']).sum()[["Total Energy Generated(MWh)"]]
df_new.reset_index()
df = df.set_index("Year")
df_total_energy_generated = df_total_energy_generated.set_index("Year")
df_new.reset_index(inplace=True)
df_new = df_new.set_index("Year")
df = df[df["State"].str.contains("CA|CO|MT|MN|NY|VT|VA|WA")]
df_new = df_new[df_new["State"].str.contains("CA|CO|MT|MN|NY|VT|VA|WA")]
df_total_energy_generated = df_total_energy_generated[df_total_energy_generated["State"].str.contains("CA|CO|MT|MN|NY|VT|VA|WA")]
df_new.reset_index(inplace = True)
df.reset_index(inplace = True)
df_total_energy_generated.reset_index(inplace = True)
df = df[df["Energy Source"].str.contains("Total")]
df = df.drop(df.columns[[2, 3]], axis=1)
df.reset_index(inplace = True)
df["Renewable Energy Generated(MWh)"] = df_new["Total Energy Generated(MWh)"]
df["Proportion"] = df_new["Total Energy Generated(MWh)"] / df_total_energy_generated["Total Energy Generated(MWh)"]

df.head(8)

,index,Year,State,Total Energy Generated(MWh),Renewable Energy Generated(MWh),Proportion
0,0,2011,CA,200804842.48,51198133.28,0.254965
1,4,2011,CO,51432554.29,7387578.84,0.143636
2,8,2011,MN,53120061.49,7471843.46,0.14066
3,11,2011,MT,30128542.57,13861048.95,0.460064
4,14,2011,NY,137480346.95,30831499.62,0.224261
5,18,2011,VA,66670859.07,1210389.00,0.018155
6,20,2011,VT,6776218.81,1459733.00,0.21542
7,24,2011,WA,115262600.82,98080921.71,0.850934